//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kielan.ExpertSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patterns
    {
        public Patterns()
        {
            this.Rules = new HashSet<Rules>();
            this.Rule = new HashSet<Rules>();
        }
    
        public long Id { get; set; }
        public long RulesId { get; set; }
        public double Cf { get; set; }
    
        public virtual Facts Facts { get; set; }
        public virtual ICollection<Rules> Rules { get; set; }
        public virtual ICollection<Rules> Rule { get; set; }
    }
}
